-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cathegories
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cathegories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.manufacturers
(
    id integer NOT NULL DEFAULT nextval('manufacturer_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT manufacturer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_tovars
(
    order_id integer NOT NULL,
    tovar_articul character varying(20) COLLATE pg_catalog."default" NOT NULL,
    count integer NOT NULL,
    CONSTRAINT order_tovars_pkey PRIMARY KEY (order_id, tovar_articul)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    order_date date NOT NULL,
    delivery_date date NOT NULL,
    point_of_delivery_id integer NOT NULL,
    user_id integer NOT NULL,
    code integer NOT NULL,
    status_id integer NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.points_of_delivery
(
    id integer NOT NULL DEFAULT nextval('point_of_delivery_id_seq'::regclass),
    address character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT point_of_delivery_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.statuses
(
    id integer NOT NULL DEFAULT nextval('status_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    id integer NOT NULL DEFAULT nextval('supplier_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT supplier_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tovars
(
    article character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    unit_id integer NOT NULL,
    cost integer NOT NULL,
    supplier_id integer NOT NULL,
    manufacturer_id integer NOT NULL,
    cathegory_id integer NOT NULL,
    sale integer NOT NULL,
    count integer NOT NULL,
    descryption character varying(300) COLLATE pg_catalog."default" NOT NULL,
    photo character varying(300) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tovars_pkey PRIMARY KEY (article)
);

CREATE TABLE IF NOT EXISTS public.units
(
    id serial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT units_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    id serial NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    role_id integer NOT NULL,
    fio character varying(100) COLLATE pg_catalog."default" NOT NULL,
    login character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.order_tovars
    ADD CONSTRAINT "order" FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_tovars
    ADD CONSTRAINT tovar FOREIGN KEY (tovar_articul)
    REFERENCES public.tovars (article) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT address FOREIGN KEY (point_of_delivery_id)
    REFERENCES public.points_of_delivery (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT status FOREIGN KEY (status_id)
    REFERENCES public.statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT "user" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tovars
    ADD CONSTRAINT cathegory FOREIGN KEY (cathegory_id)
    REFERENCES public.cathegories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tovars
    ADD CONSTRAINT manufacturer FOREIGN KEY (manufacturer_id)
    REFERENCES public.manufacturers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tovars
    ADD CONSTRAINT supplier FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tovars
    ADD CONSTRAINT unit FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT role FOREIGN KEY (role_id)
    REFERENCES public.user_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
